name: Fetch realtor feeds & styles

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Read data/realtors.json
        id: list
        run: |
          set -euo pipefail
          FILE="data/realtors.json"
          if [ ! -f "$FILE" ]; then
            echo "Missing data/realtors.json" >&2
            exit 1
          fi
          jq -r '.realtors | to_entries[] | @base64' "$FILE" > /tmp/entries.txt
          echo "Prepared $(wc -l </tmp/entries.txt) entries"

      - name: Fetch per realtor
        run: |
          set -euo pipefail
          mkdir -p data assets/css/themes
          while read -r line; do
            [ -n "$line" ] || continue
            obj=$(echo "$line" | base64 --decode)
            uuid=$(echo "$obj" | jq -r '.value.uuid')
            feed=$(echo "$obj" | jq -r '.value.feed')
            css_src=$(echo "$obj" | jq -r '.value.stylesheet_src')
            css_dst=$(echo "$obj" | jq -r '.value.stylesheet_local')
            name=$(echo "$obj" | jq -r '.value.name')

            echo "== $name ($uuid) =="

            if [ -n "$feed" ] && curl -fsSL --max-time 25 --retry 2 --retry-delay 2 -H "Accept: application/json" "$feed" -o "/tmp/realtor.json"; then
              if jq -e . "/tmp/realtor.json" >/dev/null 2>&1; then
                mv "/tmp/realtor.json" "data/realtor-${uuid}.json"
                echo "feed -> data/realtor-${uuid}.json"
              else
                echo "WARN invalid JSON for $name"
              fi
            else
              echo "WARN could not fetch feed for $name"
            fi

            if [ -n "$css_src" ] && curl -fsSL --max-time 25 --retry 2 --retry-delay 2 "$css_src" -o "/tmp/theme.css"; then
              mkdir -p "$(dirname "$css_dst")"
              mv "/tmp/theme.css" "$css_dst"
              echo "css  -> $css_dst"
            else
              echo "WARN could not fetch css for $name"
            fi
          done < /tmp/entries.txt

      - name: Commit & push
        run: |
          set -euo pipefail
          if [[ -n "$(git status --porcelain data assets/css/themes)" ]]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add data assets/css/themes
            git commit -m "Update realtor feeds & themes [skip ci]"
            git push
            echo "Changes committed."
          else
            echo "No changes to commit."
          fi
